# Generated by Django 5.1.3 on 2024-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.CharField(default=str, max_length=100),
        ),
    ]
